export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  CLIENT_UPGRADE_REQUIRED: 'CLIENT_UPGRADE_REQUIRED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth & Devices
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  DEVICE_NOT_APPROVED: 'DEVICE_NOT_APPROVED',
  DEVICE_PENDING: 'DEVICE_PENDING',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  DEVICE_LIMIT_REACHED: 'DEVICE_LIMIT_REACHED',
  INVALID_DEVICE_SIGNATURE: 'INVALID_DEVICE_SIGNATURE',
  SESSION_REVOKED: 'SESSION_REVOKED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  INVALID_TWO_FACTOR_CODE: 'INVALID_TWO_FACTOR_CODE',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',

  // Shifts & Tracking
  SHIFT_ALREADY_OPEN: 'SHIFT_ALREADY_OPEN',
  NO_OPEN_SHIFT: 'NO_OPEN_SHIFT',
  SHIFT_STATE_INVALID: 'SHIFT_STATE_INVALID',
  SEGMENT_OUTSIDE_SHIFT: 'SEGMENT_OUTSIDE_SHIFT',
  SEGMENT_OVERLAP: 'SEGMENT_OVERLAP',
  SEGMENT_TOO_OLD: 'SEGMENT_TOO_OLD',

  // CRM & Mail
  LEAD_DUPLICATE: 'LEAD_DUPLICATE',
  MAILBOX_UNAVAILABLE: 'MAILBOX_UNAVAILABLE',
  MAILBOX_TOKEN_REVOKED: 'MAILBOX_TOKEN_REVOKED',
  MAIL_ACTION_FORBIDDEN: 'MAIL_ACTION_FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiErrorResponse {
  error: {
    code: ErrorCode;
    message: string;
    details?: Record<string, unknown>;
    requestId?: string;
  };
}
